# Generated by Django 5.2.8 on 2025-11-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_account_number',
            field=models.CharField(blank=True, help_text='Account number for bank transfers', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Additional payment instructions', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='payment_till_number',
            field=models.CharField(blank=True, help_text='Till number for offline payment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
