# Generated by Django 5.2.8 on 2025-12-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_payment_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
