# Generated by Django 5.2.8 on 2025-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_booking_mpesa_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notification_email',
            field=models.EmailField(blank=True, help_text='Email to receive booking notifications', max_length=254, null=True),
        ),
    ]
