# Generated by Django 5.2.8 on 2025-12-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mpesa_transaction_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
