# Generated by Django 5.2.8 on 2025-12-10 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking_mpesa_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the group or individual artist', max_length=200)),
                ('category', models.CharField(choices=[('DANCE', 'Dance'), ('COMEDY', 'Comedy'), ('SONG', 'Song'), ('OTHER', 'Other')], max_length=20)),
                ('number_of_performers', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='events.event')),
            ],
        ),
    ]
