# Generated by Django 5.2.8 on 2025-12-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes or requirements for the performance.', null=True),
        ),
    ]
