# Generated by Django 5.2.8 on 2025-11-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('TIKTOK', 'TikTok'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube')], max_length=20)),
                ('url', models.URLField(help_text='Link to the social media post')),
                ('caption', models.TextField(blank=True, help_text='Optional caption or description')),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage feed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
