# Generated by Django 5.2.8 on 2025-11-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('TIKTOK', 'TikTok'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('FACEBOOK', 'Facebook')], max_length=20, unique=True)),
                ('profile_url', models.URLField(help_text='URL to the social media profile')),
                ('display_name', models.CharField(blank=True, help_text='Display name for the profile (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Show in footer and other areas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Profile',
                'verbose_name_plural': 'Social Profiles',
                'ordering': ['platform'],
            },
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='platform',
            field=models.CharField(choices=[('TIKTOK', 'TikTok'), ('INSTAGRAM', 'Instagram'), ('YOUTUBE', 'YouTube'), ('FACEBOOK', 'Facebook')], max_length=20),
        ),
    ]
