# Generated by Django 4.2.25 on 2025-11-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_socialprofile_alter_socialpost_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='embed_code',
            field=models.TextField(blank=True, help_text='Paste the full embed code here (iframe, blockquote, etc.)'),
        ),
    ]
