# Generated by Django 4.2.25 on 2025-11-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_socialpost_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='author',
            field=models.CharField(blank=True, help_text='Author/channel name', max_length=200),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='comment_count',
            field=models.BigIntegerField(default=0, help_text='Number of comments'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='like_count',
            field=models.BigIntegerField(default=0, help_text='Number of likes'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='published_date',
            field=models.DateTimeField(blank=True, help_text='Date published', null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the video/post', max_length=500),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='view_count',
            field=models.BigIntegerField(default=0, help_text='Number of views'),
        ),
    ]
