# Generated by Django 4.2.25 on 2025-11-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_socialpost_author_socialpost_comment_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='embed_code',
            field=models.TextField(blank=True, default='', help_text='Paste the full embed code here (iframe, blockquote, etc.)'),
        ),
    ]
