# Generated by Django 4.2.25 on 2025-11-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_alter_socialpost_embed_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('TIKTOK', 'TikTok'), ('YOUTUBE', 'YouTube'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram')], max_length=20)),
                ('channel_url', models.URLField(help_text='URL to the social media channel/profile')),
                ('channel_identifier', models.CharField(help_text='Unique identifier for the channel (e.g., username, ID)', max_length=200, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Display name for the channel', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Enable automatic feed fetching for this channel')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last time the feed was synced', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Social Media Channel',
                'verbose_name_plural': 'Social Media Channels',
                'ordering': ['-created_at'],
            },
        ),
    ]
